// <auto-generated />
using Customer.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Customer.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240514135816_customers")]
    partial class customers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Customer")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Customer.Domain.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Clients", "Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Client 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Client 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Client 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Client 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Client 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Client 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Client 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Client 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Client 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Client 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Client 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Client 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Client 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Client 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Client 15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Client 16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Client 17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Client 18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Client 19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Client 20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Client 21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Client 22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Client 23"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Client 24"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Client 25"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Client 26"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Client 27"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Client 28"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Client 29"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Client 30"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
