// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240422122212_init-catalog")]
    partial class initcatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Products", "Catalog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "product description 1",
                            Name = "Product 1",
                            Price = 710m
                        },
                        new
                        {
                            Id = 2,
                            Description = "product description 2",
                            Name = "Product 2",
                            Price = 390m
                        },
                        new
                        {
                            Id = 3,
                            Description = "product description 3",
                            Name = "Product 3",
                            Price = 1517m
                        },
                        new
                        {
                            Id = 4,
                            Description = "product description 4",
                            Name = "Product 4",
                            Price = 1566m
                        },
                        new
                        {
                            Id = 5,
                            Description = "product description 5",
                            Name = "Product 5",
                            Price = 661m
                        },
                        new
                        {
                            Id = 6,
                            Description = "product description 6",
                            Name = "Product 6",
                            Price = 977m
                        },
                        new
                        {
                            Id = 7,
                            Description = "product description 7",
                            Name = "Product 7",
                            Price = 494m
                        },
                        new
                        {
                            Id = 8,
                            Description = "product description 8",
                            Name = "Product 8",
                            Price = 792m
                        },
                        new
                        {
                            Id = 9,
                            Description = "product description 9",
                            Name = "Product 9",
                            Price = 441m
                        },
                        new
                        {
                            Id = 10,
                            Description = "product description 10",
                            Name = "Product 10",
                            Price = 220m
                        },
                        new
                        {
                            Id = 11,
                            Description = "product description 11",
                            Name = "Product 11",
                            Price = 296m
                        },
                        new
                        {
                            Id = 12,
                            Description = "product description 12",
                            Name = "Product 12",
                            Price = 806m
                        },
                        new
                        {
                            Id = 13,
                            Description = "product description 13",
                            Name = "Product 13",
                            Price = 1516m
                        },
                        new
                        {
                            Id = 14,
                            Description = "product description 14",
                            Name = "Product 14",
                            Price = 425m
                        },
                        new
                        {
                            Id = 15,
                            Description = "product description 15",
                            Name = "Product 15",
                            Price = 1703m
                        },
                        new
                        {
                            Id = 16,
                            Description = "product description 16",
                            Name = "Product 16",
                            Price = 758m
                        },
                        new
                        {
                            Id = 17,
                            Description = "product description 17",
                            Name = "Product 17",
                            Price = 1161m
                        },
                        new
                        {
                            Id = 18,
                            Description = "product description 18",
                            Name = "Product 18",
                            Price = 1453m
                        },
                        new
                        {
                            Id = 19,
                            Description = "product description 19",
                            Name = "Product 19",
                            Price = 1096m
                        },
                        new
                        {
                            Id = 20,
                            Description = "product description 20",
                            Name = "Product 20",
                            Price = 1567m
                        },
                        new
                        {
                            Id = 21,
                            Description = "product description 21",
                            Name = "Product 21",
                            Price = 170m
                        },
                        new
                        {
                            Id = 22,
                            Description = "product description 22",
                            Name = "Product 22",
                            Price = 737m
                        },
                        new
                        {
                            Id = 23,
                            Description = "product description 23",
                            Name = "Product 23",
                            Price = 860m
                        },
                        new
                        {
                            Id = 24,
                            Description = "product description 24",
                            Name = "Product 24",
                            Price = 441m
                        },
                        new
                        {
                            Id = 25,
                            Description = "product description 25",
                            Name = "Product 25",
                            Price = 710m
                        },
                        new
                        {
                            Id = 26,
                            Description = "product description 26",
                            Name = "Product 26",
                            Price = 1175m
                        },
                        new
                        {
                            Id = 27,
                            Description = "product description 27",
                            Name = "Product 27",
                            Price = 1696m
                        },
                        new
                        {
                            Id = 28,
                            Description = "product description 28",
                            Name = "Product 28",
                            Price = 938m
                        },
                        new
                        {
                            Id = 29,
                            Description = "product description 29",
                            Name = "Product 29",
                            Price = 1752m
                        },
                        new
                        {
                            Id = 30,
                            Description = "product description 30",
                            Name = "Product 30",
                            Price = 1638m
                        },
                        new
                        {
                            Id = 31,
                            Description = "product description 31",
                            Name = "Product 31",
                            Price = 1668m
                        },
                        new
                        {
                            Id = 32,
                            Description = "product description 32",
                            Name = "Product 32",
                            Price = 1834m
                        },
                        new
                        {
                            Id = 33,
                            Description = "product description 33",
                            Name = "Product 33",
                            Price = 1239m
                        },
                        new
                        {
                            Id = 34,
                            Description = "product description 34",
                            Name = "Product 34",
                            Price = 432m
                        },
                        new
                        {
                            Id = 35,
                            Description = "product description 35",
                            Name = "Product 35",
                            Price = 1476m
                        },
                        new
                        {
                            Id = 36,
                            Description = "product description 36",
                            Name = "Product 36",
                            Price = 966m
                        },
                        new
                        {
                            Id = 37,
                            Description = "product description 37",
                            Name = "Product 37",
                            Price = 118m
                        },
                        new
                        {
                            Id = 38,
                            Description = "product description 38",
                            Name = "Product 38",
                            Price = 609m
                        },
                        new
                        {
                            Id = 39,
                            Description = "product description 39",
                            Name = "Product 39",
                            Price = 594m
                        },
                        new
                        {
                            Id = 40,
                            Description = "product description 40",
                            Name = "Product 40",
                            Price = 350m
                        },
                        new
                        {
                            Id = 41,
                            Description = "product description 41",
                            Name = "Product 41",
                            Price = 1961m
                        },
                        new
                        {
                            Id = 42,
                            Description = "product description 42",
                            Name = "Product 42",
                            Price = 906m
                        },
                        new
                        {
                            Id = 43,
                            Description = "product description 43",
                            Name = "Product 43",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 44,
                            Description = "product description 44",
                            Name = "Product 44",
                            Price = 310m
                        },
                        new
                        {
                            Id = 45,
                            Description = "product description 45",
                            Name = "Product 45",
                            Price = 1477m
                        },
                        new
                        {
                            Id = 46,
                            Description = "product description 46",
                            Name = "Product 46",
                            Price = 746m
                        },
                        new
                        {
                            Id = 47,
                            Description = "product description 47",
                            Name = "Product 47",
                            Price = 906m
                        },
                        new
                        {
                            Id = 48,
                            Description = "product description 48",
                            Name = "Product 48",
                            Price = 292m
                        },
                        new
                        {
                            Id = 49,
                            Description = "product description 49",
                            Name = "Product 49",
                            Price = 626m
                        },
                        new
                        {
                            Id = 50,
                            Description = "product description 50",
                            Name = "Product 50",
                            Price = 1156m
                        },
                        new
                        {
                            Id = 51,
                            Description = "product description 51",
                            Name = "Product 51",
                            Price = 515m
                        },
                        new
                        {
                            Id = 52,
                            Description = "product description 52",
                            Name = "Product 52",
                            Price = 1192m
                        },
                        new
                        {
                            Id = 53,
                            Description = "product description 53",
                            Name = "Product 53",
                            Price = 1231m
                        },
                        new
                        {
                            Id = 54,
                            Description = "product description 54",
                            Name = "Product 54",
                            Price = 462m
                        },
                        new
                        {
                            Id = 55,
                            Description = "product description 55",
                            Name = "Product 55",
                            Price = 1223m
                        },
                        new
                        {
                            Id = 56,
                            Description = "product description 56",
                            Name = "Product 56",
                            Price = 396m
                        },
                        new
                        {
                            Id = 57,
                            Description = "product description 57",
                            Name = "Product 57",
                            Price = 854m
                        },
                        new
                        {
                            Id = 58,
                            Description = "product description 58",
                            Name = "Product 58",
                            Price = 996m
                        },
                        new
                        {
                            Id = 59,
                            Description = "product description 59",
                            Name = "Product 59",
                            Price = 1381m
                        },
                        new
                        {
                            Id = 60,
                            Description = "product description 60",
                            Name = "Product 60",
                            Price = 131m
                        },
                        new
                        {
                            Id = 61,
                            Description = "product description 61",
                            Name = "Product 61",
                            Price = 1969m
                        },
                        new
                        {
                            Id = 62,
                            Description = "product description 62",
                            Name = "Product 62",
                            Price = 179m
                        },
                        new
                        {
                            Id = 63,
                            Description = "product description 63",
                            Name = "Product 63",
                            Price = 897m
                        },
                        new
                        {
                            Id = 64,
                            Description = "product description 64",
                            Name = "Product 64",
                            Price = 1515m
                        },
                        new
                        {
                            Id = 65,
                            Description = "product description 65",
                            Name = "Product 65",
                            Price = 617m
                        },
                        new
                        {
                            Id = 66,
                            Description = "product description 66",
                            Name = "Product 66",
                            Price = 1646m
                        },
                        new
                        {
                            Id = 67,
                            Description = "product description 67",
                            Name = "Product 67",
                            Price = 370m
                        },
                        new
                        {
                            Id = 68,
                            Description = "product description 68",
                            Name = "Product 68",
                            Price = 1432m
                        },
                        new
                        {
                            Id = 69,
                            Description = "product description 69",
                            Name = "Product 69",
                            Price = 974m
                        },
                        new
                        {
                            Id = 70,
                            Description = "product description 70",
                            Name = "Product 70",
                            Price = 608m
                        },
                        new
                        {
                            Id = 71,
                            Description = "product description 71",
                            Name = "Product 71",
                            Price = 285m
                        },
                        new
                        {
                            Id = 72,
                            Description = "product description 72",
                            Name = "Product 72",
                            Price = 992m
                        },
                        new
                        {
                            Id = 73,
                            Description = "product description 73",
                            Name = "Product 73",
                            Price = 1069m
                        },
                        new
                        {
                            Id = 74,
                            Description = "product description 74",
                            Name = "Product 74",
                            Price = 971m
                        },
                        new
                        {
                            Id = 75,
                            Description = "product description 75",
                            Name = "Product 75",
                            Price = 1465m
                        },
                        new
                        {
                            Id = 76,
                            Description = "product description 76",
                            Name = "Product 76",
                            Price = 1735m
                        },
                        new
                        {
                            Id = 77,
                            Description = "product description 77",
                            Name = "Product 77",
                            Price = 1835m
                        },
                        new
                        {
                            Id = 78,
                            Description = "product description 78",
                            Name = "Product 78",
                            Price = 1315m
                        },
                        new
                        {
                            Id = 79,
                            Description = "product description 79",
                            Name = "Product 79",
                            Price = 496m
                        },
                        new
                        {
                            Id = 80,
                            Description = "product description 80",
                            Name = "Product 80",
                            Price = 615m
                        },
                        new
                        {
                            Id = 81,
                            Description = "product description 81",
                            Name = "Product 81",
                            Price = 813m
                        },
                        new
                        {
                            Id = 82,
                            Description = "product description 82",
                            Name = "Product 82",
                            Price = 422m
                        },
                        new
                        {
                            Id = 83,
                            Description = "product description 83",
                            Name = "Product 83",
                            Price = 1666m
                        },
                        new
                        {
                            Id = 84,
                            Description = "product description 84",
                            Name = "Product 84",
                            Price = 854m
                        },
                        new
                        {
                            Id = 85,
                            Description = "product description 85",
                            Name = "Product 85",
                            Price = 533m
                        },
                        new
                        {
                            Id = 86,
                            Description = "product description 86",
                            Name = "Product 86",
                            Price = 1595m
                        },
                        new
                        {
                            Id = 87,
                            Description = "product description 87",
                            Name = "Product 87",
                            Price = 1756m
                        },
                        new
                        {
                            Id = 88,
                            Description = "product description 88",
                            Name = "Product 88",
                            Price = 120m
                        },
                        new
                        {
                            Id = 89,
                            Description = "product description 89",
                            Name = "Product 89",
                            Price = 630m
                        },
                        new
                        {
                            Id = 90,
                            Description = "product description 90",
                            Name = "Product 90",
                            Price = 1334m
                        },
                        new
                        {
                            Id = 91,
                            Description = "product description 91",
                            Name = "Product 91",
                            Price = 1178m
                        },
                        new
                        {
                            Id = 92,
                            Description = "product description 92",
                            Name = "Product 92",
                            Price = 953m
                        },
                        new
                        {
                            Id = 93,
                            Description = "product description 93",
                            Name = "Product 93",
                            Price = 1926m
                        },
                        new
                        {
                            Id = 94,
                            Description = "product description 94",
                            Name = "Product 94",
                            Price = 771m
                        },
                        new
                        {
                            Id = 95,
                            Description = "product description 95",
                            Name = "Product 95",
                            Price = 1198m
                        },
                        new
                        {
                            Id = 96,
                            Description = "product description 96",
                            Name = "Product 96",
                            Price = 1883m
                        },
                        new
                        {
                            Id = 97,
                            Description = "product description 97",
                            Name = "Product 97",
                            Price = 940m
                        },
                        new
                        {
                            Id = 98,
                            Description = "product description 98",
                            Name = "Product 98",
                            Price = 898m
                        },
                        new
                        {
                            Id = 99,
                            Description = "product description 99",
                            Name = "Product 99",
                            Price = 568m
                        },
                        new
                        {
                            Id = 100,
                            Description = "product description 100",
                            Name = "Product 100",
                            Price = 1991m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks", "Catalog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Stock = 362
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Stock = 181
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Stock = 376
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Stock = 61
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            Stock = 94
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            Stock = 208
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Stock = 205
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 8,
                            Stock = 115
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 9,
                            Stock = 41
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 10,
                            Stock = 121
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 11,
                            Stock = 350
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 12,
                            Stock = 396
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 13,
                            Stock = 329
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 14,
                            Stock = 361
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 15,
                            Stock = 140
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 16,
                            Stock = 85
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 17,
                            Stock = 77
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 18,
                            Stock = 322
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 19,
                            Stock = 255
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 20,
                            Stock = 337
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 21,
                            Stock = 392
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 22,
                            Stock = 492
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 23,
                            Stock = 340
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 24,
                            Stock = 208
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 25,
                            Stock = 442
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 26,
                            Stock = 125
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 27,
                            Stock = 13
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 28,
                            Stock = 497
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 29,
                            Stock = 195
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 30,
                            Stock = 35
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 31,
                            Stock = 98
                        },
                        new
                        {
                            Id = 32,
                            ProductId = 32,
                            Stock = 14
                        },
                        new
                        {
                            Id = 33,
                            ProductId = 33,
                            Stock = 66
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 34,
                            Stock = 338
                        },
                        new
                        {
                            Id = 35,
                            ProductId = 35,
                            Stock = 336
                        },
                        new
                        {
                            Id = 36,
                            ProductId = 36,
                            Stock = 490
                        },
                        new
                        {
                            Id = 37,
                            ProductId = 37,
                            Stock = 294
                        },
                        new
                        {
                            Id = 38,
                            ProductId = 38,
                            Stock = 46
                        },
                        new
                        {
                            Id = 39,
                            ProductId = 39,
                            Stock = 498
                        },
                        new
                        {
                            Id = 40,
                            ProductId = 40,
                            Stock = 338
                        },
                        new
                        {
                            Id = 41,
                            ProductId = 41,
                            Stock = 348
                        },
                        new
                        {
                            Id = 42,
                            ProductId = 42,
                            Stock = 212
                        },
                        new
                        {
                            Id = 43,
                            ProductId = 43,
                            Stock = 177
                        },
                        new
                        {
                            Id = 44,
                            ProductId = 44,
                            Stock = 416
                        },
                        new
                        {
                            Id = 45,
                            ProductId = 45,
                            Stock = 307
                        },
                        new
                        {
                            Id = 46,
                            ProductId = 46,
                            Stock = 124
                        },
                        new
                        {
                            Id = 47,
                            ProductId = 47,
                            Stock = 444
                        },
                        new
                        {
                            Id = 48,
                            ProductId = 48,
                            Stock = 131
                        },
                        new
                        {
                            Id = 49,
                            ProductId = 49,
                            Stock = 321
                        },
                        new
                        {
                            Id = 50,
                            ProductId = 50,
                            Stock = 148
                        },
                        new
                        {
                            Id = 51,
                            ProductId = 51,
                            Stock = 49
                        },
                        new
                        {
                            Id = 52,
                            ProductId = 52,
                            Stock = 210
                        },
                        new
                        {
                            Id = 53,
                            ProductId = 53,
                            Stock = 364
                        },
                        new
                        {
                            Id = 54,
                            ProductId = 54,
                            Stock = 57
                        },
                        new
                        {
                            Id = 55,
                            ProductId = 55,
                            Stock = 7
                        },
                        new
                        {
                            Id = 56,
                            ProductId = 56,
                            Stock = 247
                        },
                        new
                        {
                            Id = 57,
                            ProductId = 57,
                            Stock = 284
                        },
                        new
                        {
                            Id = 58,
                            ProductId = 58,
                            Stock = 35
                        },
                        new
                        {
                            Id = 59,
                            ProductId = 59,
                            Stock = 318
                        },
                        new
                        {
                            Id = 60,
                            ProductId = 60,
                            Stock = 223
                        },
                        new
                        {
                            Id = 61,
                            ProductId = 61,
                            Stock = 93
                        },
                        new
                        {
                            Id = 62,
                            ProductId = 62,
                            Stock = 443
                        },
                        new
                        {
                            Id = 63,
                            ProductId = 63,
                            Stock = 60
                        },
                        new
                        {
                            Id = 64,
                            ProductId = 64,
                            Stock = 317
                        },
                        new
                        {
                            Id = 65,
                            ProductId = 65,
                            Stock = 253
                        },
                        new
                        {
                            Id = 66,
                            ProductId = 66,
                            Stock = 22
                        },
                        new
                        {
                            Id = 67,
                            ProductId = 67,
                            Stock = 374
                        },
                        new
                        {
                            Id = 68,
                            ProductId = 68,
                            Stock = 2
                        },
                        new
                        {
                            Id = 69,
                            ProductId = 69,
                            Stock = 96
                        },
                        new
                        {
                            Id = 70,
                            ProductId = 70,
                            Stock = 227
                        },
                        new
                        {
                            Id = 71,
                            ProductId = 71,
                            Stock = 355
                        },
                        new
                        {
                            Id = 72,
                            ProductId = 72,
                            Stock = 281
                        },
                        new
                        {
                            Id = 73,
                            ProductId = 73,
                            Stock = 320
                        },
                        new
                        {
                            Id = 74,
                            ProductId = 74,
                            Stock = 229
                        },
                        new
                        {
                            Id = 75,
                            ProductId = 75,
                            Stock = 303
                        },
                        new
                        {
                            Id = 76,
                            ProductId = 76,
                            Stock = 300
                        },
                        new
                        {
                            Id = 77,
                            ProductId = 77,
                            Stock = 287
                        },
                        new
                        {
                            Id = 78,
                            ProductId = 78,
                            Stock = 157
                        },
                        new
                        {
                            Id = 79,
                            ProductId = 79,
                            Stock = 11
                        },
                        new
                        {
                            Id = 80,
                            ProductId = 80,
                            Stock = 480
                        },
                        new
                        {
                            Id = 81,
                            ProductId = 81,
                            Stock = 73
                        },
                        new
                        {
                            Id = 82,
                            ProductId = 82,
                            Stock = 261
                        },
                        new
                        {
                            Id = 83,
                            ProductId = 83,
                            Stock = 489
                        },
                        new
                        {
                            Id = 84,
                            ProductId = 84,
                            Stock = 178
                        },
                        new
                        {
                            Id = 85,
                            ProductId = 85,
                            Stock = 240
                        },
                        new
                        {
                            Id = 86,
                            ProductId = 86,
                            Stock = 263
                        },
                        new
                        {
                            Id = 87,
                            ProductId = 87,
                            Stock = 361
                        },
                        new
                        {
                            Id = 88,
                            ProductId = 88,
                            Stock = 327
                        },
                        new
                        {
                            Id = 89,
                            ProductId = 89,
                            Stock = 298
                        },
                        new
                        {
                            Id = 90,
                            ProductId = 90,
                            Stock = 343
                        },
                        new
                        {
                            Id = 91,
                            ProductId = 91,
                            Stock = 385
                        },
                        new
                        {
                            Id = 92,
                            ProductId = 92,
                            Stock = 273
                        },
                        new
                        {
                            Id = 93,
                            ProductId = 93,
                            Stock = 7
                        },
                        new
                        {
                            Id = 94,
                            ProductId = 94,
                            Stock = 267
                        },
                        new
                        {
                            Id = 95,
                            ProductId = 95,
                            Stock = 68
                        },
                        new
                        {
                            Id = 96,
                            ProductId = 96,
                            Stock = 359
                        },
                        new
                        {
                            Id = 97,
                            ProductId = 97,
                            Stock = 42
                        },
                        new
                        {
                            Id = 98,
                            ProductId = 98,
                            Stock = 145
                        },
                        new
                        {
                            Id = 99,
                            ProductId = 99,
                            Stock = 429
                        },
                        new
                        {
                            Id = 100,
                            ProductId = 100,
                            Stock = 66
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
